### ISSUE TITLE
请问有没有安装部署文档呢，我在phpstorm上没有运行起来呢

### ISSUE THREAD

**Issue by wenchangming211** [uicestone/LubanLock#21]

**Comment by uicestone** [comment]
你好，这玩意比较老了……年久失修，请问阁下要跑起来作甚？

**Comment by wenchangming211** [comment]
感觉里面的日历日常安排功能挺不错的，想用下，平时可以根据日历记录日常工作，管理团队周报
不止能否提供安装部署文档，或者您🈶️其他的开源项目类似，谢谢🙏

**Comment by uicestone** [comment]
用过 [Teambition](https://www.teambition.com/) 吗？

**Comment by wenchangming211** [comment]
Teambition 不是开源项目哦，跟我们目前在用的禅道又很类似。

**Comment by wenchangming211** [comment]
启动起来报这个错误：
Parse error: syntax error, unexpected '[' in /var/www/html/application/models/Object.php on line 206
A PHP Error was encountered

Severity: Parsing Error

Message: syntax error, unexpected '['

Filename: models/Object.php

Line Number: 206

Backtrace:

**Comment by wenchangming211** [comment]
lubanlock.people这个表不存在呢
[root@localhost _doc]# mysql -ulubanlock -plubanlock lubanlock < upgrade.sql
ERROR 1146 (42S02) at line 2: Table 'lubanlock.people' doesn't exist
[root@localhost _doc]#

**Comment by uicestone** [comment]
你可以登录 http://luban.uice.lu 看看，真的啥都没有，这个项目很早就被遗忘了，虽然当时想了很多
用户名：guest1
密码：guest

**Comment by wenchangming211** [comment]
https://github.com/uicestone/Syssh 这个工程的截图上🈶️很多东西啊，介绍上说继承者是您

**Comment by uicestone** [comment]
Syssh是我再之前（2011-2012年）的时候一个更早的项目，在律师事务所和学校用过。界面同项目内截图。

**Comment by uicestone** [comment]
如果你想要日历管理功能，要不要试试沿用我的数据结构、思路等，但使用现在的框架和技术重新写一个？

**Comment by wenchangming211** [comment]
是嘛，我现在就很想搭Syssh这个项目，里面🈶️很多东西还是不错的哦，能不能提供下支持或者安装部署文档啊，多谢🙏

**Comment by uicestone** [comment]
如果你要直接用，还是Syssh比较靠谱，当时确实花了不少时间的。我要不抽时间跑跑看吧

**Comment by uicestone** [comment]
我去部署看看Syssh项目

**Comment by wenchangming211** [comment]
实际上我这边已经有个不错的周报系统了，但是就是缺少通过日历的方式记录每天的工作内容，我看Syssh上面就有这个功能，我那个工程是python 的flask框架的，

**Comment by uicestone** [comment]
那你如何结合两套系统？

**Comment by wenchangming211** [comment]
那就实在太感谢🙏您了，请问大哥现在在哪里发展从事什么工作，能加您微信或者扣扣吗

**Comment by wenchangming211** [comment]
考虑🈶️两种方式，一是借鉴您的日历周报功能在我那套上面开发一个模块，二是把您这套拿过来改掉，以日历周报为基础，您这个项目类似于谷歌日历还不错哦

**Comment by wenchangming211** [comment]
哈喽大哥，https://github.com/uicestone/Syssh 我今天部署了一下没启动起来，请问🈶️空能指导一下吗

**Comment by uicestone** [comment]
uicestone 我微信号
